### ISSUE TITLE
Multiple sensors

### ISSUE THREAD

**Issue by knom** [Strixx76/mold_risk_index#1]
Is it possible to use multiple instances for multiple pairs of sensors?
(e. g. basement and attic)

thx.

**Comment by Strixx76** [comment]
Yes you can. Just click "Configuration" -> "Integrations" and add the integration a second or third time...
I will update the instructions next week.

**Comment by Strixx76** [comment]
Fixed with 99fd797751321efaf51147614774d858de1c3b27
