### ISSUE TITLE
Difference between HA mold 

### ISSUE THREAD

**Issue by spuljko** [Strixx76/mold_risk_index#2]
Can documentation be updated with differences from HA  mold indicator integration?
https://www.home-assistant.io/integrations/mold_indicator/

**Comment by Strixx76** [comment]
The ["Mold Indicator"](https://www.home-assistant.io/integrations/mold_indicator/) integration is for calculating the risk of mold in a heated moist space with a surface chilled by the outside air temperature, for example a bathroom with a window. There the humidity in the room will rise close to the cold surface and even risk to precipitate if the difference is too great or if the humidity is too high in the room. The documentation says: "_If the sensor value rises above approximately 70 percent, mold growth might occur..._" and this is true for temperatures of 20°C and above, but not for lower temperatures.

This integration calculates the risk of mold in a not heated confined space, like an unventilated [crawl space](https://en.wikipedia.org/wiki/Crawl_space), only taking the temperature and humidity in count. Here you normally have colder temperatures (in my part of the world) most time of the year, and no surfaces that is colder than the air inside. This means you can allow a higher humidity without the risk of mold. This integration can also be used for a not heated garage or attic for example.

**Comment by Strixx76** [comment]
Fixed with 99fd797751321efaf51147614774d858de1c3b27
