### ISSUE TITLE
Plot image - annotation spelling

### ISSUE THREAD

**Issue by ClaudiuCudla** [Strixx76/mold_risk_index#3]
Hello and thank you for this integration work 💪 I'll try it out - after seeing it on the BeardedTinker channel on youtube.

Just wanted to ask if the image `plot.png` - describes areas on the left, bottom and right - that are much too cold or much too hot or too dry for condensation/mold to appear?
If so, then the correct terms should be "Too cold", "Too dry" and "Too hot" instead of "To".

Thank you!

**Comment by Strixx76** [comment]
Thanks for noticing the typo. I will fix it ASAP.
And also update README.md with a link of an English paper on the subject where the curves are originating from.

I never thought this was of interest for anyone not living in an Scandinavian country...

**Comment by ClaudiuCudla** [comment]
Thank you! Mold doesn't care about the region it seems 😂

**Comment by Strixx76** [comment]
Fixed with cf16baa233220ae2bc759b79d3649200f20e4790
