### ISSUE TITLE
An extension collaboration ? 

### ISSUE THREAD

**Issue by tomtom13** [Strixx76/mold_risk_index#6]
Hi,
I found your integration by accident and I find it useful already.
I would like to extend it, but before I bluntly fork it I wanted to run it past you.

I'm using your integration for bathrooms - and I started considering to use the indicated risk for triggering the dehumidifiers / forced ventilation. However to my mind there is one important thing missing. As you said - you used graphs from craw space graphs. In bathrooms it's often that air temp will be greatly higher than wall / window - which during winter will have greatly different temp and increase local humidity.

I've considered extending your integration by:
- providing an additional sensor input for outside temperature
- providing a predicted insulation coefficient ( in % )
- providing an configuration "at whih risk level engage dehumidification / ventilation" 
- provide configuration in form of offset - how low (in % of humidity) below the risk, keep on dehumidifying / venting
- provide a simple trigger output / "true/false" value for triggering the dehumidification / veltilation

This could be enabled by choosing "advanced operation" and of course I would code that my self, but I would prefer this to be part of your integration rather than pointless duplication.

**Comment by Strixx76** [comment]
Hello,

Some of your ideas I also had initially (and some more), but then decided to drop them because I want to keep it simple and easy to maintain.

> - providing an additional sensor input for outside temperature
> - providing a predicted insulation coefficient ( in % )

For this you can already use the native mold integration: [Mold Indicator](https://www.home-assistant.io/integrations/mold_indicator/)

> - providing an configuration "at which risk level engage dehumidification / ventilation"
> - provide configuration in form of offset - how low (in % of humidity) below the risk, keep on dehumidifying / venting
> - provide a simple trigger output / "true/false" value for triggering the dehumidification / veltilation

This is easier done by an automation than adding code to the integration and complicate the setup process. My suggestion is that you make an automation blueprint and share with the community. You should also considering adding a hysteresis.

**Comment by tomtom13** [comment]
So about the "mold indicator" the fact that you have to edit configuration.yaml - that's dumb, HA still don't understand that to get to "the masses" you need to have it done simply. Also their documentation is double confusing for creating multiple sensors. But hey, it's just me.
The blueprints at this stage are a dog mess. I've tried to find something that would eliminate ample of node red stuff that I have for hue scene automation, and after a day of searching I gave up. 

My goal is to give people a simple (gui) advanced solution that would not break becuase HA decided to change the config structure and now their HA doesn't start - do you remember how min / max was only a configuration thing ? now it's nice gui thing.

**Comment by Strixx76** [comment]
If you don't want to use advanced automation you can achieve what you want by using the [Generic hygrostat](https://www.home-assistant.io/integrations/generic_hygrostat/) in dehumidifier mode and then you only need a simple automation to set humidity (with the [service set_humidity](https://www.home-assistant.io/integrations/humidifier/#service-humidifierset_humidity) from either this integration or the native mold integration.

If the only set back is that you want the ability to set up the integrations from the UI I think it is better to add that to the [Generic hygrostat](https://www.home-assistant.io/integrations/generic_hygrostat/) and [Mold Indicator](https://www.home-assistant.io/integrations/mold_indicator/)

The solution is not to merge two existing integrations into to this integration just to get the config flows.
